# File: cortexfeed/knowledge/graph/graph_search.py

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


class GraphSearch:
    """
    Query interface for Project Intelligence graphs.

    Supports:

    - file lookup
    - symbol lookup
    - route lookup
    - dependency lookup
    - reference lookup

    Consumes graph.json generated by GraphBuilder.
    """

    def __init__(
        self,
        graph_path: str | Path,
    ) -> None:
        self.graph_path = Path(graph_path)

        if not self.graph_path.exists():
            raise FileNotFoundError(
                f"Graph file not found: {self.graph_path}"
            )

        with self.graph_path.open(
            "r",
            encoding="utf-8",
        ) as handle:
            self.graph = json.load(handle)

        self.nodes = self.graph["nodes"]
        self.edges = self.graph["edges"]

    def find_file(
        self,
        file_name: str,
    ) -> list[dict[str, Any]]:
        matches: list[dict[str, Any]] = []

        target = file_name.lower()

        for node in self.nodes:
            if node["node_type"] != "file":
                continue

            if node["name"].lower() == target:
                matches.append(node)

        return matches

    def find_symbol(
        self,
        symbol_name: str,
    ) -> list[dict[str, Any]]:
        matches: list[dict[str, Any]] = []

        target = symbol_name.lower()

        for node in self.nodes:
            if node["node_type"] not in {
                "class",
                "function",
                "method",
            }:
                continue

            if node["name"].lower() == target:
                matches.append(node)

        return matches

    def find_route(
        self,
        route_path: str,
    ) -> list[dict[str, Any]]:
        matches: list[dict[str, Any]] = []

        for node in self.nodes:
            if node["node_type"] != "route":
                continue

            if node["name"] == route_path:
                matches.append(node)

        return matches

    def find_dependencies(
        self,
        file_path: str,
    ) -> list[dict[str, Any]]:
        dependencies: list[dict[str, Any]] = []

        for edge in self.edges:
            if edge["relationship"] != "imports":
                continue

            if edge["source"] != file_path:
                continue

            dependencies.append(
                {
                    "source": edge["source"],
                    "target": edge["target"],
                }
            )

        return dependencies

    def find_dependents(
        self,
        file_path: str,
    ) -> list[dict[str, Any]]:
        dependents: list[dict[str, Any]] = []

        for edge in self.edges:
            if edge["relationship"] != "imports":
                continue

            if edge["target"] != file_path:
                continue

            dependents.append(
                {
                    "source": edge["source"],
                    "target": edge["target"],
                }
            )

        return dependents

    def find_references(
        self,
        symbol_name: str,
    ) -> list[dict[str, Any]]:
        references: list[dict[str, Any]] = []

        for edge in self.edges:
            if edge["relationship"] != "defines":
                continue

            target_node = self.get_node(
                edge["target"]
            )

            if target_node is None:
                continue

            if (
                target_node["name"].lower()
                != symbol_name.lower()
            ):
                continue

            source_node = self.get_node(
                edge["source"]
            )

            references.append(
                {
                    "file": source_node,
                    "symbol": target_node,
                }
            )

        return references

    def get_node(
        self,
        node_id: str,
    ) -> dict[str, Any] | None:
        for node in self.nodes:
            if node["id"] == node_id:
                return node

        return None

    def search(
        self,
        query: str,
    ) -> list[dict[str, Any]]:
        query_lower = query.lower()

        results: list[dict[str, Any]] = []

        for node in self.nodes:
            if query_lower in node[
                "name"
            ].lower():
                results.append(node)

        return results

    def neighbors(
        self,
        node_id: str,
    ) -> list[dict[str, Any]]:
        connected: list[dict[str, Any]] = []

        for edge in self.edges:
            if edge["source"] == node_id:
                target = self.get_node(
                    edge["target"]
                )

                if target is not None:
                    connected.append(
                        {
                            "relationship": edge[
                                "relationship"
                            ],
                            "node": target,
                        }
                    )

        return connected

    def statistics(
        self,
    ) -> dict[str, int]:
        counts: dict[str, int] = {}

        for node in self.nodes:
            node_type = node["node_type"]

            counts[node_type] = (
                counts.get(node_type, 0) + 1
            )

        return counts


def load_graph_search(
    graph_path: str | Path,
) -> GraphSearch:
    return GraphSearch(graph_path)